# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gizzmo}
  s.version = "0.8.0.a1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kyle Maxwell"]
  s.date = %q{2010-09-20}
  s.description = %q{Gizzmo is a command-line client for managing gizzard clusters.}
  s.email = %q{kmaxwell@twitter.com}
  s.executables = ["gizzmo", "setup_shards"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/gizzmo",
     "bin/setup_shards",
     "gizzmo.gemspec",
     "lib/gizzard.rb",
     "lib/gizzard/commands.rb",
     "lib/gizzard/digest.rb",
     "lib/gizzard/migrator.rb",
     "lib/gizzard/nameserver.rb",
     "lib/gizzard/shard_template.rb",
     "lib/gizzard/thrift.rb",
     "lib/gizzard/transformation.rb",
     "lib/gizzmo.rb",
     "lib/vendor/thrift_client/simple.rb",
     "spec/shard_template_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/transformation_spec.rb",
     "test/config.yaml",
     "test/expected/deep.txt",
     "test/expected/dry-wrap-table_b_0.txt",
     "test/expected/empty-file.txt",
     "test/expected/find-only-sql-shard-type.txt",
     "test/expected/forwardings.txt",
     "test/expected/help-info.txt",
     "test/expected/info.txt",
     "test/expected/links-for-replicating_table_b_0.txt",
     "test/expected/links-for-table_b_0.txt",
     "test/expected/links-for-table_repl_0.txt",
     "test/expected/original-find.txt",
     "test/expected/subtree-info.txt",
     "test/expected/subtree.txt",
     "test/expected/unwrapped-replicating_table_b_0.txt",
     "test/expected/unwrapped-table_b_0.txt",
     "test/expected/wrap-table_b_0.txt",
     "test/helper.rb",
     "test/recreate.sql",
     "test/test.sh"
  ]
  s.homepage = %q{http://github.com/twitter/gizzmo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Gizzmo is a command-line client for managing gizzard clusters.}
  s.test_files = [
    "spec/shard_template_spec.rb",
     "spec/spec_helper.rb",
     "spec/transformation_spec.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

